# Generated by Django 2.2.1 on 2019-05-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaleAqui',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('assunto', models.CharField(max_length=100)),
                ('mensagem', models.TextField(max_length=300)),
            ],
        ),
    ]
