# Generated by Django 2.2.1 on 2019-05-20 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horasBemApp', '0005_aluno_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='usuario',
        ),
    ]
